# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    name: 'Testing release'
    env:
      NEW_VERSION: ${{ github.event.inputs.new_version }}
    steps:
      - name: Extract current branch
        run: |
          echo "TARGET_BRANCH=${GITHUB_REF#"refs/"*/}" >> $GITHUB_ENV
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - name: Get Current Version
        run: |
          echo "VERSION=0.0.5" >> $GITHUB_ENV
          echo "Current Version is: $VERSION"
      
      - name: Create Awesome Badge
        uses: schneegans/dynamic-badges-action@v1.1.0
        with:
          auth: ${{ secrets.GIST_PAT }}
          gistID: 9ab197d84cab86c98e0e43db1942b17b
          filename: test_version_badge.json
          label: version
          message: ${{ env.VERSION }}
          color: orange

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo $TARGET_BRANCH
          echo $NEW_VERSION
          echo Add other actions to build,
          echo test, and deploy your project.
